### ISSUE TITLE
Upgrade to ocamlformat.0.26.1

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#1]
The project is currently using `ocamlformat.0.18.0` which is quite old and prevents us from using `dune.3.0` or higher if we want to. We'd like to use the latest version instead.

To do this, we need to update the content of `.ocamlformat`, in particular the `version` field and format the project again.

We should also add a `.git-blame-ignore-revs` file for this reformatting and future ones not to pollute the history when using `git blame`. Simply add a line with the hash of the commit with the above changes in the newly added `.git-blame-ignore-revs` with a comment indicating what it corresponds to.

**Comment by MungaSoftwiz** [comment]
Can I be assigned to this issue please?

I have checked the file and from my understanding what is needed is to upgrade the version of `.ocamlformat` to a newer version, track changes with `.git-blame-ignore-revs` and ensure build runs.

**Comment by dinakajoy** [comment]
Yea, go for it @MungaSoftwiz

**Comment by MungaSoftwiz** [comment]
I was installing the `ocamlformat.0.18.0` and noticed it has quite a lot of dependencies to install. 

Considering that I'll have to install the `ocamlformat.0.26.1`, is it advisable to just install the latest version and work from there?
Or is the `ocamlformat.0.18.0` coupled to `merlin` and `ocp-indent`?

**Comment by NathanReb** [comment]
No you don't have to install 0.18.0 and can jump straight to 0.26.1 indeed! Since you are going to bump the version you won't even be able to format with the older version anyway!

**Comment by NathanReb** [comment]
Also note that `merlin` and `ocp-indent` are "nice to have" dev dependencies but are not strictly required to work on the project. I should probably update the CONTRIBUTING.md guide to reflect.

I do strongly recommend that you still install them though!

**Comment by MungaSoftwiz** [comment]
Thank you for the advice. I use vim and I saw they support the editor with their config files. So I agree they are "nice to haves".

**Comment by MungaSoftwiz** [comment]
I am done with this task and I just have one question. 

I did format the project and it gave an output of correct formatting. But are the formatted files to be pushed or only the two files stated above?

**Comment by NathanReb** [comment]
Yes you need to commit the reformatted files along with the version change in `.ocamlformat`. The CI check for formatting will fail otherwise as it checks that every PR is correctly formatted.

You should add the `.git-blame-ignore-revs` update in a separate commit as you'll need to know the above mentionned commit hash to do so.

**Comment by MungaSoftwiz** [comment]
I see some syntax but not sure which is the reformatted file to be committed. From my point of view I think it's `bin/api_diff.ml` but I'm not entirely sure.
```
munga@SAMSUNG:~/ocaml-api-watch-fork$ dune build @fmt --auto-promote
File "bin/api_diff.ml", line 1, characters 0-0:
diff --git a/_build/default/bin/api_diff.ml b/_build/default/bin/.formatted/api_diff.ml
index be21441..2f135fc 100644
--- a/_build/default/bin/api_diff.ml
+++ b/_build/default/bin/.formatted/api_diff.ml
@@ -32,7 +32,5 @@ let info =
     ~doc:"List API changes between two versions of a library"

 let term = Cmdliner.Term.(const run $ ref_cmi $ current_cmi)
-
 let main = Cmdliner.Cmd.v info term
-
 let () = Stdlib.exit @@ Cmdliner.Cmd.eval main
Promoting _build/default/bin/.formatted/api_diff.ml to bin/api_diff.ml.
```

**Comment by NathanReb** [comment]
According to the diff, yes, `bin/api_diff.ml` has been reformatted.

After updating the version in `.ocamlformat` and running `dune build @fmt --auto-promote` you should be able to commit all modified tracked files.

Simply run `git commit -a` at this point to include all the relevant changes.

**Comment by shonfeder** [comment]
Closed by #7 :tada:

**Comment by MungaSoftwiz** [comment]
I just realised there is an issue with my commit message. It says `Upgrade project to use ocamlformat.0.21.1`.
I would kindly likely to ask for the mentors point of view on this. I'm aware that it might be misleading to future contributors and I'm really sorry about that type of commit.

I was requesting to change it to `Upgrade project to use ocamlformat.0.26.1`,
My initial thought was to perform a git interactive rebase and ammend the present commit message with a new one without affecting the file components.

Please let me know how you would like me to approach this. @NathanReb @shonfeder @dinakajoy

**Comment by NathanReb** [comment]
I'll do the rebase myself, don't worry. Thanks for notifying us!
