### ISSUE TITLE
Add test cases for diffing changes to modules

### ISSUE THREAD

**Issue by shonfeder** [NathanReb/ocaml-api-watch#10]
Having a few simple test cases for different API changes would make for a great way to monitor progress on `api-diff` initial implementation.

Add tests that will check the behavior of `api-diff` when

- [ ] Adding a module
- [ ] Removing a module
- [ ] Modifying an existing module

Those tests should be added to `tests/api-diff/run.t`. This will require either modifying the existing `ref.mli` file created in that test, or creating a new `mod_ref.mli` file, because `ref.mli` doesn't include a module already. For each test case we should generate a new `.mli` file with a change from the list above, compile it to a `.cmi` with `ocamlc` and then run `api-diff ref.cmi <test-file.cmi>`.

You can read about the testing methodology used for the tests at https://github.com/NathanReb/ocaml-api-watch/blob/main/CONTRIBUTING.md#writing-tests

**Comment by Dezzy12** [comment]
Can you please assign me this issue @NathanReb

**Comment by Payne680** [comment]
@shonfeder please can assign me this task cause am available to work on it asap

**Comment by dinakajoy** [comment]
@Dezzy12 are you still interested in this task?

**Comment by harshey1103** [comment]
@shonfeder please assign me this issue.

**Comment by harshey1103** [comment]
Just one small question.
Should I open a new PR or continue with existing PR on this issue?

**Comment by shonfeder** [comment]
Whichever you prefer!
