### ISSUE TITLE
Upgrade to OCaml 4.14

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#2]
The project should be using a more recent version of OCaml. Since we rely on the compiler libraries at the moment, we depend on a fixed version of OCaml, currently 4.12.

We should update the `dune-project` file to reflect this change. From there, running `dune build api-watch.opam` will update the opam file accordingly.

In the current project state I don't expect there to be a breaking change to the parts of the compiler libs we are using between 4.12 and 4.14 but we never know.

**Comment by MungaSoftwiz** [comment]
From my understanding this task needs an upgrade of the current OCaml version. So updating the `dune-project` file and running the command `dune build api-watch.opam` will update opam files in the project.

So we need to upgrade our local environment from 4.12 to 4.14 to be able to complete the task if I'm not mistaken.

**Comment by MungaSoftwiz** [comment]
Requesting assignment for the project above.

**Comment by MungaSoftwiz** [comment]
So I am beginning the task and I had an issue concerning the upgrade from 4.12 to 4.14. Is it possible to just upgrade the version without essentially deleting the present version of the switch in OCaml?

Like an upgrade of files to fit the 4.14 version.

**Comment by shonfeder** [comment]
Changing the ocaml version will require rebuilding the local switch. You can use

    opam switch reinstall .

After building the updated opam file and that should sort you out!

**Comment by MungaSoftwiz** [comment]
Thank you for the recommendations @shonfeder. I see that this upgrades to the latest available release of OCaml if I not wrong.
The latest version from online Docs is 5.1.1 so for 4.14 do we append the version to the `opam switch reinstall` phrase?

**Comment by dinakajoy** [comment]
You can run `opam switch reinstall --switch 4.14.1` or whatever switch you are upgrading to

**Comment by MungaSoftwiz** [comment]
Thank you @dinakajoy. I think I'll go with the 4.14.1 since it has bug fixed from the .14 version before it.

**Comment by shonfeder** [comment]
If using a local switch, then the switch should be decided based on the ocaml version specified in the opam file. So if that's now working something may be amiss with your set up? Or maybe you are not using a local switch?

**Comment by MungaSoftwiz** [comment]
Yes I am using a local sqitch. This is what the .opam file indicates:
```
 depends: [
    "dune" {>= "2.7"}
    "ocaml" {>= "4.12.0" & < "4.13.0"}
    "logs"
```
From the above snippet those are the two allowed versions. How do I go about that?

**Comment by dinakajoy** [comment]
All good at @MungaSoftwiz

**Comment by NathanReb** [comment]
The way I would proceed here the following:
1. Without reinstalling your switch, update `dune-project` to bump the lower and upper bounds on ocaml
2. Have dune update the opam file with `dune build api-watch.opam`
3. Reinstall your switch and try to build the project under 4.14

For 3 you can probably simply remove the local switch and create a new one from there. Given you're changing compiler version you will have to rebuild everything anyway.

**Comment by NathanReb** [comment]
The project relies on the compiler libraries so to avoid compatibility issues we'll stick to allowing only 4.14, i.e. `>= 4.14.0 & < 5.0.0`.

**Comment by MungaSoftwiz** [comment]
I am done with this particular task. The builds runs on my local switch as expected.

**Comment by shonfeder** [comment]
Awesome work! We'll be ready to review your PR when you are ready with it :)

**Comment by MungaSoftwiz** [comment]
I still have a simple question though. Do we have to run `dune build @fmt --auto-promote` after each build we run.

**Comment by NathanReb** [comment]
`dune build @fmt --auto-promote` will reformat OCaml source files (`.ml` and `.mli`) and dune files (`dune` and
`dune-project`). If you haven't modified or written any new such files there is no need to run the command.

Either way, the CI will fail if the project is not correctly formatted so you can't really miss it.

**Comment by MungaSoftwiz** [comment]
Thanks for the clear explanation. I was a bit confused about that since I had not done so in my recent PR. I clearly understand when to run the the formatter now.
