### ISSUE TITLE
The diff comparison is not catching removed types

### ISSUE THREAD

**Issue by shonfeder** [NathanReb/ocaml-api-watch#23]
As observed by @harshey1103 at https://github.com/NathanReb/ocaml-api-watch/pull/19#issuecomment-1985055868, and then demonstrated by @MungaSoftwiz in #16, the way we are using `Includemod.signatures` does not account for the removal of types.

@NathanReb has noted that we will probably end up moving away from `Includemod.signatures`, but in the meantime we should be able to account for this by also calling `Includemod.signatuer` with the arguments `current` and `reference` arguments flipped. This was also suggested by @harshey1103.

**Comment by MungaSoftwiz** [comment]
Can you please assign this issue to me?

**Comment by harshey1103** [comment]
Can I work on this issue since I have an idea how to do it and I have already implemented it in my local branch?

**Comment by shonfeder** [comment]
Hello! I think it makes sense for @harshey1103 to work on this issue, partially because they already have been touching this code directly in #19 and partially because they first called out this problem and proposed the interim solution.

@MungaSoftwiz, I will work on preparing an interesting issue for you. I should have something ready by tomorrow.

**Comment by shonfeder** [comment]
@harshey1103 considering that #13 will be moving the run function, do you think you could approach the issue as follows, in order to avoid merge conflicts and colliding work?

Instead of changing the run function in `bin/api_diff.ml`, write a new function implementing

```ocaml
val signatures_are_identical : Types.signature_item list -> Types.signature_item list -> bool
```

This function will take the signatures accessed by `current.cmi_sign` and `reference.cmi_sign` and test whether they are identical, using the logic you proposed, returning `true` if they are the and `false` otherwise.

Most of the logic in this function can be taken directly from the current `run` function, and perhaps you have already implemented this locally. You can add this function to the file https://github.com/nathanreb/ocaml-api-watch/tree/main/lib/api_watch_diff.ml and then we can replace the logic in the `run` function with a call to your function once it is in place.

What do you think?

**Comment by shonfeder** [comment]
@harshey1103 this issue has a lot of overlap with #13, because both involve refactoring the core logic of the `run` function in `bin/api_diff.ml`. Depending which of these is completed first, we may need to resolve some merge conflicts. Just FYI. I am happy to help with this.

Please ignore my previous message!

**Comment by MungaSoftwiz** [comment]
> Hello! I think it makes sense for @harshey1103 to work on this issue, partially because they already have been touching this code directly in #19 and partially because they first called out this problem and proposed the interim solution.
> 
> @MungaSoftwiz, I will work on preparing an interesting issue for you. I should have something ready by tomorrow.

Okay @shonfeder. Looking forward to it.

**Comment by Siddhi-agg** [comment]
@shonfeder I have understood this issue and since @harshey1103 has already created a PR for it, that has been reviewed and is almost done, I am continuously following its progress to know the changes I will require for #13. 


> @shonfeder I have understood what we are trying to achieve in #13. I'd be happy to help @Siddhi-agg on #13, given my PR is merged before. We'll ask for your help if the need arises :)

Sure! I would love to work with you, if any conflicts arise.

**Comment by shonfeder** [comment]
Hi, @MungaSoftwiz. Just a quick update that us mentors will need to talk on Monday to clarify the next steps for the project before opening more issues. Sorry for the delay.

**Comment by MungaSoftwiz** [comment]
> Hi, @MungaSoftwiz. Just a quick update that us mentors will need to talk on Monday to clarify the next steps for the project before opening more issues. Sorry for the delay.

No problem @shonfeder. Thank you for the update.
