### ISSUE TITLE
Add expect tests setup for the api-watch.diff library

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#27]
At the moment we have a test suite for the `api-diff` tool using cram tests.

Since we want to also provide libraries within this package and we recently extracted the core logic for diffing OCaml interfaces into `api-watch.diff`, we will need to also have an extensive test suite for the library itself.

Those tests should live in a new `tests/api-watch-diff` folder.

## ppx_expect inline tests

We'd like to use `ppx_expect` tests.

`ppx_expect` tests are very similar to cram tests but with OCaml code instead of command line. You can read a bit about our cram tests [here](https://github.com/NathanReb/ocaml-api-watch/blob/main/CONTRIBUTING.md#writing-tests).

It allows you to write OCaml code that prints to the standard output and to ensure that what's printed corresponds to our expectations.

The content of an expect test file will look like a series of such entries:
```ocaml
let%expect_test "test_addition" =
  let result = 1 + 1 in
  Format.printf "%i" result;
  [%expect {|2|}]
```

The `let%expect_test "name" = body` part is used to declare an individual expect test. The expect test `body` should contain the actual test logic and a series of statements printing the relevant values to stdout, in the above it's the `Format.printf ...` statement, followed by a `[%expect s]` where `s` is a string, corresponding to the expected output of the print above.

When running `dune runtest`, if the test fails, you'll get a diff showing that the actual output differed from the expected one. This change can then be accepted and promoted to the test file with `dune promote` if the new output is correct.

To learn how to set them up you can look at [dune's documentation](https://dune.readthedocs.io/en/latest/tests.html#inline-expectation-tests) and [`ppx_expect`'s documentation](https://github.com/janestreet/ppx_expect?tab=readme-ov-file#introduction).

We'll start by simply providing the test setup for this issue and will leave writing actually meaningful tests for later.
To ensure that everything works you can add a single test that `Api_watch_diff.diff_interface ~reference:[] ~current;[]` is `false`.

**Comment by Siddhi-agg** [comment]
@NathanReb Since I haven't worked on the tests yet, I would like to work on this.

**Comment by MungaSoftwiz** [comment]
I am available

> @Siddhi-agg @harshey1103 @MungaSoftwiz if you are interested pls let me know and I'll assign one of you.
> 
> Once this is completed I'll add other issues for writing some tests here and eventually add a test helpers library.

I am available and interested @NathanReb

**Comment by NathanReb** [comment]
@Siddhi-agg I'm assigning you to this issue!

Don't worry @harshey1103 and @MungaSoftwiz, there will be follow up issues after this one!

**Comment by Siddhi-agg** [comment]
@NathanReb I am also interested in the follow up issues which will follow this one. Please assign me when they are created.
