### ISSUE TITLE
Upgrade to OCaml 5.1

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#28]
Let's upgrade our compiler version to the latest.

This is very similar to #2 so refer to this issue for details on how to proceed.

I haven't looked at the changes between 4.14 and 5.01 in the compiler libraries so I'm not sure if this upgrade will be seemless or will require changes to our code but I'll gladly guide you if it does.

**Comment by Siddhi-agg** [comment]
@NathanReb I would really like to work on #27 since that is a medium issue and would get me a chance to work with the tests but if that is not assigned to me, I would like to work on this one. (I'm also available to work on both the issues).

**Comment by iAlexeze** [comment]
Hi @NathanReb 
I would like to work on this issue as a good first issue seeing I will be contributing for the first time in the api-watch project.

**Comment by NathanReb** [comment]
@Siddhi-agg I assigned you to a more complex issue as you have already made contributions to the project.

@mridulsrivastavaa or @nawarajshah would you be interested in taking care of this?

@iAlexeze I'm really sorry, I'll try to favor applicants who already showed interest before but couldn't contribute before because all issues were taken. If they are not interested anymore and do not manifest I will gladly assign this to you!

**Comment by nawarajshah** [comment]
@NathanReb yes i am intrested

**Comment by mridulsrivastavaa** [comment]
> @Siddhi-agg I assigned you to a more complex issue as you have already made contributions to the project.
> 
> @mridulsrivastavaa or @nawarajshah would you be interested in taking care of this?
> 
> @iAlexeze I'm really sorry, I'll try to favor applicants who already showed interest before but couldn't contribute before because all issues were taken. If they are not interested anymore and do not manifest I will gladly assign this to you!

Yes, I am interested in contributing in this issue .

**Comment by nawarajshah** [comment]
I have made a pull request, @NathanReb can you please review this?

**Comment by NathanReb** [comment]
I assigned @nawarajshah since they got here first. I'll try to think of another good first issue @mridulsrivastavaa but you should also look for other projects in the meantime as I can't guarantee you'll get a chance to contribute here unfortunately.

**Comment by mridulsrivastavaa** [comment]
> I assigned @nawarajshah since they got here first. I'll try to think of another good first issue @mridulsrivastavaa but you should also look for other projects in the meantime as I can't guarantee you'll get a chance to contribute here unfortunately.

If any good first issue gets open please assign me to it. Meanwhile I'll look for other projects to contribute to.
