### ISSUE TITLE
Add basic test cases to `tests/api-diff/run.t`

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#3]
Having a few simple test cases for different API changes would make for a great way to monitor progress on `api-diff` initial implementation.

Here's a list of simple tests that we should have:
- [ ] Adds a type
- [ ] Removes a type
- [ ] Modifies an existing type
- [ ] Adds a value
- [ ] Removes a value
- [ ] Modifies an existing value
- [ ] Adds a module
- [ ] Removes a module
- [ ] Modifies an existing module

Those tests should be added to `tests/api-diff/run.t`. We can reuse the base `ref.cmi` as the reference interface. For each test case we should generate a new `.mli` file with a change corresponding to one from the list above, compile it to a `.cmi` with `ocamlc` and run `api-diff ref.cmi <test-file.cmi>`.

**Comment by amandaguan-ag** [comment]
@NathanReb Could I be assigned to this OCaml version upgrade issue? To my understanding, the task requires upgrading the dune-project to OCaml 4.14, checking the OCaml 4.14 release notes for compatibility, ensuring the build runs smoothly, and that all tests pass without output from dune runtest.Please let me know if I missed anything.

**Comment by dinakajoy** [comment]
Hi @amandaguan-ag 
@MungaSoftwiz is already working on the #2 
You can pick any task from the list on this issue to work on. 
Just let u know the one you pick.

**Comment by harshey1103** [comment]
Hi @dinakajoy, I am Harshit Goyal, an outreachy applicant. I am really excited to work on this project. I have cloned the repo and followed through contributing.md. Could I be assigned to this issue if it is okay?

**Comment by shonfeder** [comment]
Hi, @harshey1103 and @amandaguan-ag! I have talked with the other co-mentors and I am proposing we factor this issue into 3 smaller issues. This will make it easier to track who is working on what and what contributions you all have made :) 

I will assign each of you to one of those issues, but please let me know if you prefer instead to work on a different issue! 

Please don't hesitate to reach out with questions, if you get stuck or need clarification. We are here to help!

**Comment by harshey1103** [comment]
Please assign me https://github.com/NathanReb/ocaml-api-watch/issues/8 i.e. add a test case for diffing changes to types.

**Comment by shonfeder** [comment]
@amandaguan-ag would you be interested in taking on https://github.com/NathanReb/ocaml-api-watch/issues/12 ? If so, please comment there and I will assign you!
