### ISSUE TITLE
Port cram test cases to expect tests

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#31]
Cram tests for the `api-diff` tool and expect tests for the `api-watch.diff` library have different scopes. The expect tests should cover the core logic, i.e. properly detecting and representing API changes while the cram tests should cover the I/O parts and more concrete usecases.

Both being in a very early stage there are not much difference in the set of features the tool covers on top of the library so most of the test cases in our cram test suite actually test the core logic rather than the tool itself, except for the fact that it does properly parse `.cmi` files.

It would therefore make sense to port those test cases as expect tests. We'll keep the duplicate cram for now and let the two test suites diverge as the tool evolves towards more than a mere wrapper to the library main function.

## How to port from cram to expect tests

Cram and expect tests look very similar if not for the fact that the latter use OCaml and not bash. The expect tests won't rely on external files anymore but instead manipulate OCaml values.

The main task here is to understand how to represent the interfaces described in the cram tests `.mli` files in term of OCaml's `Types.signature` and pass them to `Api_watch_diff.diff_interface` instead of generating `.cmi` files and passing them to `api-diff`.

You can look at the `Types` module from the compiler [here](https://github.com/ocaml/ocaml/blob/trunk/typing/types.mli). In particular you'll want to start from [`Types.signature`](https://github.com/ocaml/ocaml/blob/trunk/typing/types.mli#L623) which is the type expected by `Api_watch_diff.diff_interface`. From there you can follow the other type definitions to figure out how to assemble the right `signature`.
If you have trouble understanding what those types correspond to, you can take a look at the [`Parsetree` module](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L883) from compiler libs. It covers more and slightly different things than `Types` does but a subset of it is very similar an `Parsetree` is better documented so it's a good place to start.

One invocation of `api-diff` in `run.t` should roughly correspond to one `let%expect_test` in `test.ml`.

Note that you can share code in between tests in the expect test file by declaring functions and constants outside of `let%expect_test` entries. It should make the test more concise than in the cram file as it is easier to factor things in OCaml than it is with text in the cram tests.

Building `Types.signature` values for tests input will likely be more verbose than the simple text version in the cram test but the goal is also to identify what can be simplified and to extract helpers into a separate test library.

## Individual issues

This issue centralizes the description of the work but we've cut it into separate smaller issues:
- [ ] #32 
- [x] #33
- [ ] #34
- [ ] #35 

We'll eventually add more tests here to cover the full range of signature items but this makes up for a good starting set.

**Comment by NathanReb** [comment]
@harshey1103 @Siddhi-agg @MungaSoftwiz please pick the one you'd like.

I'd recommend doing #32 and #33 first as it will give us a good insight of the kind of helpers we'd need for #35 and will make it easy to share things with the test cases for #34 as modules are roughly a wrapper around some other signature items.

**Comment by MungaSoftwiz** [comment]
I think @NathanReb said that we will be creating a helper library since writing the expect tests is cumbersome. He also said that the helper library would first depend on the finishing of expect tests for values, types and modules. 
So basically the expect tests that we've written would guide us in creating a helper library in #35. This is what our mentor said if I'm not wrong.

**Comment by NathanReb** [comment]
I think there's not much value in writing new tests now given we are very likely to replace them with ones written using the `compile_interface` function from the test helpers.
