### ISSUE TITLE
Port tests for changes to types to expect tests

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#32]
This is one of the sub issues for #31.

This should cover the tests from [run.t line 39](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L39) to [run.t line 83](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L83).

Refer to the main issue for details on how to proceed.

**Comment by Siddhi-agg** [comment]
@NathanReb Can this issue be assigned to me?

**Comment by NathanReb** [comment]
I already assigned you to #33

**Comment by harshey1103** [comment]
Can I work on this issue?

**Comment by NathanReb** [comment]
Sure!

**Comment by MungaSoftwiz** [comment]
I'd love to work on this issue @NathanReb. I'm not assigned at the moment.

**Comment by NathanReb** [comment]
You're right, my bad. Closing!
