### ISSUE TITLE
Port tests for changes to values to expect tests

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#33]
This is one of the sub issues for #31.

This should cover tests from [run.t line 85](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L85) to [run.t line 133](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L133).

Refer to the main issue for details on how to proceed.

**Comment by Siddhi-agg** [comment]
@NathanReb I would like to work on this.
