### ISSUE TITLE
Port tests for changes to modules to expect tests

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#34]
This is one of the sub issues for #31.

This should cover tests from [run.t line 135](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L135) to [run.t line 195](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t#L195).

Refer to the main issue for details on how to proceed.

**Comment by MungaSoftwiz** [comment]
I'd love to work on this issue @NathanReb.

**Comment by MungaSoftwiz** [comment]
Interesting, so from my understanding after going through the docs is that we have to translate descriptions from our `.mli` files into OCaml's `Types.signature` and pass them into `Api_watch_diff.diff_interface`. I'm now reading on the abstract syntax tree and trying to understand  how to represent module signatures within it.
