### ISSUE TITLE
Add a test helper library for expect tests

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#35]
This is one of the sub issues for #31.

Refer to the main issue for details.

**Comment by NathanReb** [comment]
Given how complex and verbose it is to write our own `Types.signature` it seems that a very useful helper function for writing basic test would be one that takes as input a string corresponding to the content of an `.mli` file, parse it, compiles it to a typedtree and returns the `Types.signature` enclosed.

One could then write tests in a similar fashion to:
```ocaml
let%expect_test "..." =
  let ref_interface =
    {|
type t = int

val f : t -> string
|}
  in
  let modified_interface =
    interface ^
    {|https://v2.ocaml.org/api/String.html
val g : t -> bool
|}
  in
  let reference = Test_helpers.compile_interface ref_interface in
  let current = Test_helpers.compile_interface modified_interface in
  let result = Api_watch_diff.diff_interface ~reference ~current in
  Format.printf "%b" result;
  [%expect false]
```

This can be done using the `Parse`, `Env` and `Typemod` modules from compiler libs.

**Comment by MungaSoftwiz** [comment]
I am interested @NathanReb

**Comment by harshey1103** [comment]
Yes. I am interested and almost done with previous issue.
