### ISSUE TITLE
Initial `diff_interface` implementation

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#41]
It's time to start the core of the work and actually implement a diffing function for ocaml interfaces.

There are three parts to this work.

## Representing interface diff

We need a set of types to represent the diff between an interface. The toplevel will likely be a sum type that represents the addition, removal or modification of interface entries.

We can start with a small subset of the language, e.g. the one roughly covered by our test suite so far:
- types
- values
- modules

This would leave out type extensions, module types, classes and class types for now but would make for a good enough starting point.

The compiler defines a generic type for diffing that it uses internally (see https://github.com/ocaml/ocaml/blob/5.2.0/utils/diffing.mli). It's probably too generic and complex for our needs but it can still be a good source of inspiration!

## Implementing `diff_interface`

At the moment `Api_watch_diff.diff_interface` simply returns whether a cmi differs from another cmi or not. It does so using two calls to `Includemod.signatures`. We could consider using `Includemod.signatures` and interpret its result or the exceptions it raises but it feels overkill compared to what we're trying to achieve here.

`diff_interface` should return a value of the diff abstraction briefly described above, or rather a list of such values.

Even though we'll have our own implementation there are some things from `Includemod` we'll likely reuse such as https://github.com/ocaml/ocaml/blob/5.2.0/typing/includemod.ml#L623 which build a component table, i.e. a map from items name and kind (type, value, module, ...) to the item itself. We will definitely need a similar data structure to efficiently compare interfaces!

## Updating the test suite and tools

We probably won't change the output of the `api-diff` command line tool as part of this work so no need to rewrite any of the cram tests, simply adapting the code in `bin/api_diff.ml` to use the new return type of `diff_interface` will do.

We will want to update the expect tests for the library though. This will require adding pretty printers for our diff abstraction, which can likely be derived using any good ppx (ppx_deriving.show for instance).

**Comment by NathanReb** [comment]
CC @Siddhi-agg

**Comment by Siddhi-agg** [comment]
Commenting to be assigned this issue.

**Comment by NathanReb** [comment]
@Siddhi-agg I'm marking this as resolved, we'll add separate issues for each subgoal mentioned here when it's time!
