### ISSUE TITLE
Improve diffing of values: Abstract types

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#44]
Our current implementation is able to detect addition, deletion and modification of basic values but it is not complete and will fail to detect some value modifications properly.

We'll fix the implementation incrementally, adding new test cases to our expect tests suite and improving the implementation to support them.

The first and most important one is to make sure that abstract types with the same name are considered equal between the reference and current interfaces when adequate.

Consider the following interface:
```ocaml
type t
val x : t
```

If we use it as a reference interface and then parse the same interface from a different cmi, we expect our current implementation to report a modification of `x` when we would clearly consider those interfaces to be identical.

We should add this as a test and fix the implem to the treat the the two types `t` as equal across the two interfaces.

**Comment by NathanReb** [comment]
CC @Siddhi-agg

**Comment by Siddhi-agg** [comment]
Please assign this to me @NathanReb.
