### ISSUE TITLE
Improve diffing of values: Modified Concrete Types

### ISSUE THREAD

**Issue by Siddhi-agg** [NathanReb/ocaml-api-watch#46]
In the next step to improve diffing of concrete types, it's crucial to ensure that our implementation can correctly detect changes in values that reference concrete types (records or variants) that have undergone modifications. 

Currently, our tool may not be able to detect the various modifications (like field type modification, field addition/removal for records, and variant addition/removal, variant type modification for types) to concrete types properly and may report false positives and negatives.

### Modifying Records

We can change a record either by adding a field to it, removing a field from it or changing the type of an  field present in it.

Consider the given interface:
```
type t = { a: int }
val x : t
```
When a field is added to the record defined in `type t` like in the interface given below, a change should be detected in `val f` as it references a type which has been modified.
```
type t = { a: int; b: string }
val x : t
```
An example of field type modification was given in #45 where a change should be detected again.

### Modifying Variants

Similar to records, a variant can be added to or removed from a type. The type of a variant can also be changed to modify a type.

Consider the given interface:
```
type t = A | B of int
val x : t
```
We can modify `type t` by changing the type of variant `B` from `int` to `float` :
```
type t = A | B of float
val x : t
```
We may have to discuss which changes we want to report here as a modification to `val f` and which we don't.

After we decide on the functionality, we will add the relevant test cases to our expect test suite and fix them for our discussed use case.

**Comment by Siddhi-agg** [comment]
@NathanReb Please assign this issue to me.

**Comment by NathanReb** [comment]
This has been dealt with in #50 !
