### ISSUE TITLE
Diffing values referencing polymorphic variant types

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#51]
We don't have tests for diffing such values and it would be good to add some, making sure we have the right behaviour regarding to those, both for inlined polymorphic variant type expression and reference to named polymorphic variant types.

We should also check that it behaves properly when changing the closed/open tags (``[> `A | `B]``/``[< `A | `B]``/``[`A | `B]``) in values.

Named polymorphic variant types should be treated as any alias type is. I expect our current implem to have the right behaviour but being sure by means of testing would be great and prevent inadvertent breakage in the future!

**Comment by NathanReb** [comment]
CC @Siddhi-agg

**Comment by Siddhi-agg** [comment]
Commenting to be assigned
