### ISSUE TITLE
Diffing values referencing extensible variant types

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#52]
This is also missing from our test suite! We should add tests to make sure values referencing such types are diffed adequatly.

They should probably be treated as regular variant types when referred to in a value description.

Here again, I expect our current implementation to do the right thing but better be safe than sorry!

**Comment by NathanReb** [comment]
CC @Siddhi-agg 

Also, if you want to know more about those types, you can read through the corresponding section of the OCaml manual: https://ocaml.org/manual/5.2/extensiblevariants.html.

**Comment by Siddhi-agg** [comment]
Please assign this to me.
