### ISSUE TITLE
Improve diffing implementation

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ocaml-api-watch#60]
To diff the set of signatures we need to fold over a pair of maps representing each a version of the interface.

Our current implementation does by folding over both maps sequentially to be able to detect added and modified values in the first pass and removed values in the second pass.

This is not very efficient and folding over both is in fact possible using `Map.merge` which signature correspond exactly to what we want.

**Comment by NathanReb** [comment]
CC @Siddhi-agg

**Comment by Siddhi-agg** [comment]
@NathanReb Commenting to be assigned.
