### ISSUE TITLE
Add test cases for diffing changes to values

### ISSUE THREAD

**Issue by shonfeder** [NathanReb/ocaml-api-watch#9]
Having a few simple test cases for different API changes would make for a great way to monitor progress on `api-diff` initial implementation.

Add tests that will check the behavior of `api-diff` when

- [ ] Adding a value
- [ ] Removing a value
- [ ] Modifying an existing value

Those tests should be added to `tests/api-diff/run.t`. We can reuse the base `ref.cmi` as the reference interface. For each test case we should generate a new `.mli` file with a change from the list above, compile it to a `.cmi` with `ocamlc` and then run `api-diff ref.cmi <test-file.cmi>`.

You can read about the testing methodology used for the tests at https://github.com/NathanReb/ocaml-api-watch/blob/main/CONTRIBUTING.md#writing-tests

**Comment by harshey1103** [comment]
Can you please assign me this issue @NathanRebw

**Comment by harshey1103** [comment]
Hi, I have opened a draft PR for this issue. Please guide me on whether my approach aligns with the objectives.
